version: '3'
services:
  ghost:
    image: ghost:4.48.9
  sonarr:
    image: lscr.io/linuxserver/sonarr 
  radarr:
    image: lscr.io/linuxserver/radarr
  nginx:
    image: nginx 
    ports:
      - 80:80 
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./custom-nginx.conf:/etc/nginx/conf.d/custom-nginx.conf